### ISSUE TITLE
Do we need block categories?

### ISSUE THREAD

**Issue by tomkins** [developersociety/django-glitter#14]
When adding a block we've got a dropdown list of block types available to the user. In past we've tried to add categories to these to group them together into related bunches.

In past, we usually had the _Common_ blocks (HTML, image, text), _Forms_, and everything else for a site was grouped with the site name. In glitter we've got _App Blocks_ for most of the pre-packaged blocks.

Thoughts?

Part of me thinks that we should just remove it, as trying to figure out groups just isn't worth it.

**Comment by zatan** [comment]
My advice would be just have two categories `Defaults blocks` and
`Application blocks` so in this case we don't have to figure out groups.

On Thu, Jul 7, 2016 at 3:07 PM, Alex Tomkins <notifications@github.com>
wrote:

> When adding a block we've got a dropdown list of block types available to
> the user. In past we've tried to add categories to these to group them
> together into related bunches.
>
> In past, we usually had the *Common* blocks (HTML, image, text), *Forms*,
> and everything else for a site was grouped with the site name. In glitter
> we've got *App Blocks* for most of the pre-packaged blocks.
>
> Thoughts?
>
> Part of me thinks that we should just remove it, as trying to figure out
> groups just isn't worth it.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/blancltd/django-glitter/issues/14>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAdrqaIKJeePVUWYz_1CdCYmOKfeHTIiks5qTQgRgaJpZM4JHHUL>
> .
>



-- 
Regards,

Edvinas Jurevicius

**Comment by tomkins** [comment]
After thinking about this one...

At some point we'll probably need to limit certain blocks to specific content types. Maybe we'll have an *Author* block which is only usable on news posts. Or maybe forms should only belong on pages, etc.

So instead of categorising blocks excessively, we could just have a list of 2 categories:

```
Common
- HTML
- Image
- Text
- etc.
News Post
- Author
```

Common blocks are usable on any content type, after that we list out blocks which are limited to a specific type of page.

**Comment by hawkz** [comment]
+1

**Comment by takeontom** [comment]
Have you considered adding config to each block which provides:

* a whitelist of content types the block will work on
* a blacklist of content types which the block is not allowed on

Also perhaps add config to columns to whitelist/blacklist which blocks can appear within them.

Doing all the above might be a simple way to get these benefits:

* Ensure blocks which rely on certain content type features are only available for those content types
* For users, only seeing blocks which make sense in a certain column or content type can make things easier. E.g. if there's a "MASSIVE HEADER IMAGE" column, then it's weird to allow a "Really Small, Unimpressive Text" block to be added to it.

**Comment by hawkz** [comment]
We've discussed white/black listing a few times historically and generally think it's what we need. We've just struggled to find time in the past. Not the team is larger maybe this is something we can address. From a hazy memory - was there a performance knock on with this?

**Comment by tomkins** [comment]
Idea for this one:

```python
from glitter import columns
from glitter import templates
from glitter.layouts import PageLayout


@templates.attach('glitter_pages.Page')
class HomePage(PageLayout):
    billboard_top = columns.Column(
        width=1280, only_blocks=['blocks.Billboard'],
    )
    header = columns.Column(width=960)
    third_left = columns.Column(width=320)
    third_middle = columns.Column(
        width=320, exclude_blocks=['carousel.CarouselBlock'],
    )
    third_right = columns.Column(width=320)
    content = columns.Column(width=960)
    footer = columns.Column(width=960)

    class Meta:
        # One of these - not both!
        # Applies to the entire content type
        exclude_blocks = [
            'appname.ModelName',
            'appname.ModelName',
        ]
        only_blocks = [
            'appname.ModelName',
            'appname.ModelName',
            'appname.ModelName',
            'appname.ModelName',
        ]
```

`only_blocks` needs a better name.

Not sure if this is the best place for it. Should this be part of layouts, or part of block registration? I think one thing to think about is that if you pip install a third party block, where should the configuration for where it's allowed to be placed?

Thoughts? I'm hoping to gets the ball rolling on this one.

**Comment by zatan** [comment]
Am happy with the @tomkins solution one thing I would change is instead of using `only_blocks` stick with just `blocks`
