### ISSUE TITLE
django-glitter broken by django-glitter and django-mptt

### ISSUE THREAD

**Issue by NeolithEra** [developersociety/django-glitter#153]
Hi, users are unable to run **_django-glitter_** due to dependency conflict with _**django**_ package. As shown in the following full dependency graph of **_django-glitter_**, **_django-glitter_** requires _**django <1.10,>=1.8**_，while **_django-mptt_** requires _**django >=1.11**_.

According to pip’s _“first found wins”_ installation strategy, _**django 1.9.13**_ is the actually installed version. However, _**django 1.9.13**_ does not satisfy _**>=1.11**_.

### Dependency tree-----------
```
django-glitter - 0.2.10
| +- django(install version:1.9.13 version range:<1.10,>=1.8)
| +- django-mptt(install version:0.10.0 version range:>=0.7)
| | +- django(install version:3.0 version range:>=1.11)
| | +- django-js-asset(install version:1.2.2 version range:*)
| +- django-mptt-admin(install version:0.7.2 version range:>=0.3)
| +- django-taggit(install version:1.1.0 version range:>=0.21.3)
| | +- django(install version:3.0 version range:>=1.11)
| +- python-dateutil(install version:2.8.1 version range:>=2.6.0)
| +- sorl-thumbnail(install version:12.5.0 version range:>=12.2)
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Suggested Solution

1.	Fix your direct dependency to be **_django>=1.8_**. I have checked this revision will not affect your downstream projects now.
2.	Fix your direct dependency to be **_django-taggit <=0.22.2, >=0.21.3_** and **_django-mptt<=0.9.0_**. I have checked this revision will not affect your downstream projects now.
3.	Remove your direct dependency **_django_**, and use _**django**_ transitively introduced by **_django-mptt_**.

@ ikonitas Which solution do you prefer, 1, 2 or 3?
Please let me know your choice. I can submit a PR to solve this issue.

**Comment by tomkins** [comment]
Hi @NeolithEra.

Pin the dependencies, or specify them at install time to ensure you get a compatible version of Django / django-taggit / django-mptt, similar to `pip install django-glitter==0.2.10 django-mptt==0.8.7 django-taggit==0.22.2`.

For us, django-glitter is deprecated (we'd recommend [Wagtail](https://wagtail.io/) instead). Even if you created a PR - it's unlikely we'd be releasing a new version anytime soon.

Feel free to fork the project if you'd like to continue making improvements to it.
