### ISSUE TITLE
Finish docs

### ISSUE THREAD

**Issue by hawkz** [developersociety/django-glitter#19]
**Priority**
- [ ] Glitter pages
- [ ] Pages navigation
- [ ] Documentation per-block

**Misc**
- [ ] Explain the pattern for blocks needing javascript

**Before public launch**
- [ ] Support
- [ ] Contributing
- [ ] Editors' guide

**Comment by tomkins** [comment]
Added: Explain the pattern for blocks needing javascript.

It's a common pattern, so would be useful to add.
