### ISSUE TITLE
Don't render empty columns

### ISSUE THREAD

**Issue by tomkins** [developersociety/django-glitter#22]
If a column has no blocks, don't render it at all. We currently render an empty div:

`<div id="glitter_column_content"></div>`

On some sites, a bunch of empty divs can cause problems, so in view mode - if a column has no blocks - don't render anything for it, return an empty string. This could be useful when multiple columns are empty, eg.

```
{% if columns.footer_left or columns.footer_right %}
    <footer>
        <div class="half-column left">
            {{ columns.footer_left }}
        </div>
        <div class="half-column right">
            {{ columns.footer_right }}
        </div>
    </footer>
{% endif %}
```

In edit mode we'll always be outputting HTML so we can see the admin control elements for adding a block to a column.

I think the only question would be - do we want a toggle where we always show the empty div? If so, I'd suggest something like:

```
class Default(PageLayout):
    content = columns.Column(width=960, render_empty=True)  # Default is False
    sidebar = columns.Column(width=480)
```

However for simplicity - I think it's just easier to not render the div and tell users to use a wrapping div in their template.

Thoughts?

**Comment by rozian** [comment]
+1




-- 


Blanc Limited
Blythe Valley Innovation Centre
Central Boulevard
Solihull, B90 8AJ


+44 (0) 33 33 44 7 800
www.blanc.ltd.uk
