### ISSUE TITLE
templates.py and templates directory in same directory

### ISSUE THREAD

**Issue by tomkins** [developersociety/django-glitter#25]
We've got `glitter/templates/` for templates, and `glitter/templates.py` in the same directory, which results in the following warning:

```
django-glitter/glitter/page.py:20: ImportWarning: Not importing directory '/Users/tomkins/Python/django-glitter/glitter/templates': missing __init__.py
  from .templates import get_layout, get_templates
```

Something to worry about? Something to fix?

Bit annoying if we have to move things about just for this!

**Comment by martinphellwig** [comment]
I was not going to be too concerned with that, it does not seem to be harmful.

**Comment by tomkins** [comment]
Would prefer avoiding it by renaming it to `template.py` instead.

It's non-urgent.

**Comment by martinphellwig** [comment]
I'll ignore it for now then :-)

**Comment by martinphellwig** [comment]
Ignoring not closing ...
