### ISSUE TITLE
Testing generic view classes which require Glittered models is hard

### ISSUE THREAD

**Issue by takeontom** [developersociety/django-glitter#29]
It's difficult to test generic views which use Glittered models as Glitter reports the model is not published.

To get around this, I need to set the model's `published` property and create a corresponding version:

``` python
    obj.published = True
    obj.save()

    # Create a glitter page to go with the object
    if created:
        version = Version(
            content_type=ContentType.objects.get_for_model(obj),
            object_id=obj.id,
            template_name='glitter/sometemplate.html')
        version.generate_version()
        version.save()

        # Point to the current version
        obj.current_version = version
        obj.save()
```

Otherwise a `glitter.exceptions.GlitterUnpublishedException` is raised by this line:
- https://github.com/blancltd/django-glitter/blob/4ed077c5775c680e8ec8551700ab2d69472f197d/glitter/mixins.py#L50

This makes the Glitter more difficult than it could be for testing, and I guess for other slightly abnormal use, e.g. populating models from API calls.

**Comment by takeontom** [comment]
Providing a convenience method somewhere might help. Perhaps adding a `generate_version` method to the `GlitterMixin`, which would then work like:

```python
version=obj.generate_version('sometemplate.html')
```

Or something like:

```python
from glitter.shortcuts import version_generator
version = version_generator(obj, 'sometemplate.html')
```

**Comment by tomkins** [comment]
A method is easier to deal with.

```python
def create_version(self, template_name, save=False, owner=None):
    # save=True would call .generate_version() and give a version number
    # save=False returns a Version without a version_number
    return Version(...)
```

Maybe?

I'm not too keen on it being `generate_version`, as that could potentially be confused with `PageVersion.generate_version()`.

Although I'm not entirely happy with what I've suggested here, naming is everything - getting a good API is essential.
