### ISSUE TITLE
When testing View: AttributeError: 'WSGIRequest' object has no attribute 'user'

### ISSUE THREAD

**Issue by takeontom** [developersociety/django-glitter#30]
Glitter presumes that all requests have a `user` property:

https://github.com/blancltd/django-glitter/blob/4ed077c5775c680e8ec8551700ab2d69472f197d/glitter/page.py#L195

This causes a `AttributeError: 'WSGIRequest' object has no attribute 'user'` exception in tests.

To get my test working I had to do this:

``` python
        request = self.factory.get(
            reverse(
                'some_url_name',
                kwargs={'id': some_id}
            ),
        )
        request.user = None
```

**Comment by tomkins** [comment]
I guess we've always assumed the existence of it with the full Django test client.

When you've got the time - feel free to have a go at fixing it and a test along with it.
