### ISSUE TITLE
Reduce excessive steps to editing/publishing a page

### ISSUE THREAD

**Issue by digiology** [developersociety/django-glitter#31]
This is a civicus change but probably requires a glitter change too.

When creating a news post the user has to do an additional step to choose the template for the new Page (there is always one) and then click 'Edit' to begin editing it.

We want the following:
-go to edit view NewsPost in admin
-choose an unpublished/new NewsPost
-click 'view on site'
-we get a view to choose the Page template, this should now happen behind the scenes as there is always only one selection
-user is redirected to the news post with the glitter edit button already selected

**Comment by tomkins** [comment]
Updated the title for this to reflect the problem.

Some other thoughts:

Even if there's multiple templates available to choose from, it might be a good idea to go with a default choice to reduce the number of steps. However we'd need to figure out what the default template is for a particular content type.

Some types of content you might not want to edit them at all (events seems to be a recurring one for this), so going through the whole edit+publish process is excessive, although the UI would need to make it clear that you're immediately publishing something.
