### ISSUE TITLE
On confirmations, put positive action on the right, negative on the left

### ISSUE THREAD

**Issue by takeontom** [developersociety/django-glitter#32]
![glitter-confirmation-prompts](https://cloud.githubusercontent.com/assets/423709/18274553/da4f17c8-743a-11e6-8c02-968bb232c3ba.png)

I'd expect the "Yes, delete it" to be on the right, and the "No, thank you" to be on the left.

**Comment by hawkz** [comment]
Depends therefore if you think deleting is a positive action..? I think this came up a while ago.

@paulevansblanc thoughts?

**Comment by takeontom** [comment]
I'd argue it's not so much a reflection on the action being performed, but more that the "OK" button should always be on the right, and "Cancel" on the left.

Are you sure you want to destroy humanity?
[Cancel] [OK ]

**Comment by zatan** [comment]
Hmm you see there is no correct order on this for example Windows puts OK
first and the  Apple puts OK last.

**Comment by hawkz** [comment]
I vote to switch the order, but make the text red.. needs the nod from @paulevansblanc though

**Comment by paulevansblanc** [comment]
I vote swap too (confirm on the right, cancel on the left)
