### ISSUE TITLE
How to include block specific Javascript, CSS, etc?

### ISSUE THREAD

**Issue by takeontom** [developersociety/django-glitter#37]
Some Blocks may require their own Javascript, CSS or other statics to be included. Ideally we only want to include these files once.

The Django way to solve this problem is to use Sekizai (https://django-sekizai.readthedocs.io/en/latest/). This is used by other CRM type software, like DjangoCMS (http://docs.django-cms.org/en/release-3.3.x/how_to/custom_plugins.html#handling-media), etc.

This is just a ticket to explore and talk about potential ways forward.

**Comment by tomkins** [comment]
Just to document the thoughts we've had, the different approaches so far seem to be:

Use something similar to [Django form media](https://docs.djangoproject.com/en/1.8/topics/forms/media/). Define these per block, then when rendering the page you combine these together - and Django will remove any duplicate CSS/JS files. Downside to this one is that it's a bit hard coded when you're creating a block.

Add additional templates per block which get rendered once per page, eg. `glitter/head/carousel.html` and `glitter/footer/carousel.html`. Both of these would be optional and can contain whatever content you want. This would be more flexible for frontend templating.

There's Sekizai, though we need to look carefully if it's possible to use given our slightly quirky way of rendering columns of content before rendering the HTML.

Last but not least - there's the option of doing absolutely nothing! Users would have to edit the CSS/JS themselves when adding new block types. We'd have to document some best practice for Javascript patterns (eg. must always have some javascript at the bottom of each page in the event of that block appearing, check if a block exists and lazy load heavy javascript like Google Maps).
