### ISSUE TITLE
Make it easier to pass extra context into a block

### ISSUE THREAD

**Issue by takeontom** [developersociety/django-glitter#49]
The only way I can see to add extra context into a block when rendering is to set the `render_function` on a Block model and then re-implement the `baseblock` function, adding the extra context into the `render_to_string` call. Which isn't too nice.

A simple solution would be to add an `extra_context` argument to the `baseblock` function, this would then allow this [slightly] nicer code:

```
def render_sharebar(*args, **kwargs):
    extra_context = {'wibble': 'wobble'}
    return baseblock(*args, **kwargs, extra_context=extra_context)
```

Ultimately, perhaps Blocks should be rendered using class based views (or something similar), which would allow overriding of specific methods, e.g. `get_context`.

**Comment by tomkins** [comment]
I'm up for seeing an overhaul on this - as it's one of the weak points.

Blocks by default are a bit too dumb. By default they should have some additional context without having to resort to a custom render function - so you can figure out what page/object that block is being rendered in, the column, etc. However this needs to be used responsibly in template land, as assumptions on what type of page a block is on could cause problems.

Something class based seems like the way to go, just needs some careful thought/design.
