### ISSUE TITLE
FormBlocks get confused if there's other FormBlocks on the same page

### ISSUE THREAD

**Issue by takeontom** [developersociety/django-glitter#55]
If I add 2 FormBlocks, e.g. a Contact Form and a custom FormBlocks to the same page and submit data in one, then both blocks will attempt to process the submitted data as the action for both forms will be the current page.

At best this causes erroneous error messages. At worst it could mean incorrect data being stored.

Suggest creating a separate view to handle FormBlock form actions.

**Comment by tomkins** [comment]
One potential option might be to add some additional hidden input on the page. Such as:

```html
<input type="hidden" name="_glitter_form_{{ form.id }}" value="1">
```

And the form block view code could check that the hidden value exists before processing it.
