### ISSUE TITLE
Allow a Block's display name to be set when registering the block

### ISSUE THREAD

**Issue by takeontom** [developersociety/django-glitter#60]
The name of a block can currently only be set by using the model's `verbose_name`. Would be useful in some situations to set the block name at the point it is being registered.

Something like:

```
block_admin.site.register_block(SomeBlock, category='App Blocks', name='This is some block')
```

Use case is for when a block name is slightly dynamic. Making `verbose_name` dynamic causes fun with migrations.

**Comment by tomkins** [comment]
Yup - would be useful.

Block registration needs improvements/reworking - but being able to change the name even if the underlying block has a different class name or verbose name would be handy.
