### ISSUE TITLE
Leaving Edit mode doesn't take you back to original URL

### ISSUE THREAD

**Issue by takeontom** [developersociety/django-glitter#67]
For example:

* I go to a local Glitter site I have running: http://localhost:8000/
* Going into Edit Mode by clicking Edit takes me to http://localhost:8000/admin/glitter_pages/page/editor/edit/7/
* Leaving Edit Mode by clicking Edit again takes me to http://localhost:8000/admin/glitter_pages/page/editor/view/7/

I'd expect to be taken back to http://localhost:8000/

Clicking Publish to exit Edit Mode works as expected, I'm taken back to http://localhost:8000/

**Comment by tomkins** [comment]
Tidying up some old issues.

The edit toggle allows you to view the page you've just edited without all the edit controls.

I can partially agree that in this case it feels a bit silly, you've not really edited anything. However if you start changing things - that toggle allows you to view the same page without all the clutter.
