### ISSUE TITLE
Document middleware/exception handling

### ISSUE THREAD

**Issue by tomkins** [developersociety/django-glitter#8]
It's confusing.

**Comment by zatan** [comment]
I add doc string on middleware also I add explanation in the docs.

On Wed, Apr 20, 2016 at 4:22 PM, Alex Tomkins <notifications@github.com>
wrote:

> It's confusing.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/blancltd/django-glitter/issues/8>
>



-- 
Regards,

Edvinas Jurevicius
